### ISSUE TITLE
si.diskLayout bug on windows

### ISSUE THREAD

**Issue by flashyu** [sebhildebrandt/systeminformation#196]
### Issue Type
error info:
```events.js:182
throw er; // Unhandled 'error' event
^
Error: write EPIPE
at exports._errnoException (util.js:1024:11)
at Socket._writeGeneric (net.js:762:25)
at Socket._write (net.js:781:8)
at doWrite (_stream_writable.js:371:12)
at writeOrBuffer (_stream_writable.js:357:5)
at Socket.Writable.write (_stream_writable.js:274:11)
at Socket.write (net.js:699:40)
at process.nextTick (C:\Users\pigcms\AppData\Local\Programs\swan-ide-gui\resources\app\dist\program-compiler\2.12.15\node_modules\systeminformation\lib\util.js:240:19)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)
```
si.diskLayout will call util.powerShell()，in powerShell method will run code: 
```
const child = spawn('powershell.exe', ['-NoLogo', '-InputFormat', 'Text', '-NoExit', '-ExecutionPolicy', 'Unrestricted', '-Command', '-'], {
        stdio: 'pipe'
      });May fail，
```
child Call error not handled，If the call fails，child.stdin.write(cmd + '\n') will error

**Comment by sebhildebrandt** [comment]
@flashyu ... yes you are right, will make a fix for that ... sorry for the inconvenience!

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
