### ISSUE TITLE
New feature wifiNetworks() is undefined

### ISSUE THREAD

**Issue by mwittig** [sebhildebrandt/systeminformation#237]
**Describe the bug**

The new feature `wifiNetworks()` raises "is not a function" TypeError as it is undefined.

**To Reproduce**

1. Trial the following code snippet:
```
var si = require('systeminformation');
si.wifiNetworks().then(function (data) {
  console.log('Wifi Network Interfaces: ' + data.map(el => el.ssid).join(", "));
});
```
**Current Output**

```
si.wifiNetworks()
   ^

TypeError: si.wifiNetworks is not a function
    at Object.<anonymous> (C:\Users\marcus\IdeaProjects\systeminfo\index.js:107:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

Process finished with exit code 1
```
**Expected behavior**

Output the list of SSIDs detected by the system

**Environment (please complete the following information):**
 - systeminformation package version: 4.11.1 (latest)
 - OS: Win10
 - Hardware: Lenovo

**Additional context**
I'll file a PR to fix the issue

**Comment by sebhildebrandt** [comment]
Thank you @mwittig ... fixed both bugs. v 4.11.2 just released
