### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#24]
Hi Sebastian,

Perhaps I did something wrong, but _npm install systeminformation --save_ appears not to work:

I am attaching file npm-debug.log.

[npm-debug.txt](https://github.com/sebhildebrandt/systeminformation/files/788480/npm-debug.txt)

Also, here is the console output (though run without --save option):
```
[root@pb_stap251 ecxmon]# npm install systeminformation

> systeminformation@3.17.0 install /home/ecxcc/ecxmon/node_modules/systeminformation
> node-gyp rebuild

make: Entering directory `/home/ecxcc/ecxmon/node_modules/systeminformation/build'
  SOLINK_MODULE(target) Release/obj.target/none.node
make: g++: Command not found
make: *** [Release/obj.target/none.node] Error 127
make: Leaving directory `/home/ecxcc/ecxmon/node_modules/systeminformation/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-642.11.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ecxcc/ecxmon/node_modules/systeminformation
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 2.6.32-642.11.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "systeminformation"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! systeminformation@3.17.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the systeminformation@3.17.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the systeminformation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs systeminformation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls systeminformation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ecxcc/ecxmon/npm-debug.log
```
I am still able to run because I again downloaded 3.11.0 instead of 3.17.0.

Please let me know what's going on here; thanks!

Cordially,

Paul

**Comment by sebhildebrandt** [comment]
I guess the problem is, that g++ is missing:

`make: g++: Command not found`

you need to do:

```
apt-get install g++ 		(Debian based distributions)
sudo yum install /usr/bin/g++	(Fedora based)
```

Anyway, I need to make further investigation, because I only need this `node-gyp` thing on OS X for getting the temperature ... for the moment, the upper commands should solve your problem (hopefully)

**Comment by sebhildebrandt** [comment]
I guess `apt-get install build-essential` should also work.

**Comment by paul-bell** [comment]
I thought that *might* be the case, but I was surprised because I'm
reasonably certain that I never before had g++ installed. Perhaps something
in the package install procedure changed? Or maybe I was running on systems
with it already installed. Unsure.

I will install g++.

Thank you.

-Paul

**Comment by paul-bell** [comment]
Fixed; thank you!
