### ISSUE TITLE
 Cannot read property 'env' of undefined

### ISSUE THREAD

**Issue by impleotv** [sebhildebrandt/systeminformation#245]
Hi,

I've updated from ver. 4.11.1 to 4.11.5 and now I have this error:
`
TypeError: Cannot read property 'env' of undefined
    at Object.<anonymous> (C:\snapshot\stsupervisor\node_modules\systeminformation\lib\util.js:40:32)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:635:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\snapshot\stsupervisor\node_modules\systeminformation\lib\index.js:25:14)
`
Went to the old version, everything works. I'm running Windows.

Thanks,

Alex

**Comment by sebhildebrandt** [comment]
OK, will check it ...

**Comment by sebhildebrandt** [comment]
My fault ... sorry! Version 4.11.6 just published ... hope this works!

**Comment by impleotv** [comment]
Wow! That was quick 😃. Thanks a lot!
