### ISSUE TITLE
JSON.parse error for octal character

### ISSUE THREAD

**Issue by yunchancho** [sebhildebrandt/systeminformation#44]
It seems that si.blockDevices() doesn't handle octal string. 
My node program was exited abnormally when this error occurs.

Is there any way to avoid this error when using si.blockDevices()? 

```
{"name":"sda1" ,"type":"part" ,"size":"471859200" ,"fstype":"ntfs" ,"mountpoint":"" ,"uuid":"E29E89789E8945CF" ,"rota":"0" ,"ro":"0" ,"rm":"0" ,"tran":"" ,"serial":"" ,"label":"\xeb\xb3\xb5\xea\xb5\xac" ,"model":"" ,"owner":"root"}
                                                                                                                                                                                  ^

SyntaxError: Unexpected token x in JSON at position 178
    at JSON.parse (<anonymous>)
    at lines.filter.forEach (/snapshot/home/nemoux/nemosolution/nemocloud/admin-backend/node_modules/systeminformation/lib/filesystem.js:153:21)
    at Array.forEach (native)
    at parseBlk (/snapshot/home/nemoux/nemosolution/nemocloud/admin-backend/node_modules/systeminformation/lib/filesystem.js:152:37)
    at /snapshot/home/nemoux/nemosolution/nemocloud/admin-backend/node_modules/systeminformation/lib/filesystem.js:205:20
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
```

Thank you in advance.

**Comment by sebhildebrandt** [comment]
Hi, 

will try to check, what causes the problem and how I can avoid it.
Will come back to you as soon as I found a solution

Regards

**Comment by sebhildebrandt** [comment]
I need to test this on a windows machine ... on linux/OSX this parsing works fine ...

**Comment by sebhildebrandt** [comment]
As `\xeb\xb3\xb5\xea\xb5\xac` seems to be HEX encoded (not octal), I added a functionality to check and decode this before parsing the JSON string. Not sure, if the displayed string now is correct but it should prevent the error.
