### ISSUE TITLE
Uncatchable exception in bluetooth

### ISSUE THREAD

**Issue by Apollon77** [sebhildebrandt/systeminformation#557]
```
2021-07-16 20:35:06.007 - error: info.0 (6020) uncaught exception: EACCES: permission denied, scandir '/var/lib/bluetooth/'
2021-07-16 20:35:06.013 - error: info.0 (6020) Error: EACCES: permission denied, scandir '/var/lib/bluetooth/'
at readdirSync (fs.js:1043:3)
at getDirectories (/opt/iobroker/node_modules/systeminformation/lib/util.js:680:12)
at getFilesRecursively (/opt/iobroker/node_modules/systeminformation/lib/util.js:687:16)
at Object.getFilesInPath (/opt/iobroker/node_modules/systeminformation/lib/util.js:695:12)
at /opt/iobroker/node_modules/systeminformation/lib/bluetooth.js:98:30
at processTicksAndRejections (internal/process/task_queues.js:77:11)
2021-07-16 20:35:06.015 - error: info.0 (6020) Exception-Code: EACCES: EACCES: permission denied, scandir '/var/lib/bluetooth/'
```

**Comment by sebhildebrandt** [comment]
@Apollon77 should work now. version 5.7.8 just released.

**Comment by Apollon77** [comment]
Thank you!
