### ISSUE TITLE
Support deno

### ISSUE THREAD

**Issue by Creative-Difficulty** [sebhildebrandt/systeminformation#792]
**Is your feature request related to a problem? Please describe.**
I am looking to migrate my project to deno. After replacing every incompatible package with a deno specific or deno-native one, i noticed, that the `systeminformation` package is not yet implemented.

**Describe the solution you'd like**
A decoupling of `systeminformation` from NodeJS specific APIs and towards Web Standard APIs would tremendously help with the migration of projects that rely on this package.

**Describe alternatives you've considered**
I have considered migrating back to NodeJS, since `systeminformation` is vital to my project and i cannot find any deno-native or deno-compatible solutions that have similar features & documentation. It would also be very difficult to migrate away from this awesome package!

**Additional context**
I used `systeminformation` something like this:
```ts
import * as si from "npm:systeminformation";
import { type StaticData, type DynamicData } from "./types.ts";

// I copied the types of this package into my types.ts file so i can use them like this in deno
export let dynamicData: DynamicData = await si.getDynamicData();
const staticData: StaticData = await si.getStaticData();

setInterval(async () => {
    dynamicData = await si.getDynamicData();
}, 5000);
```
But it throws this error:
```
error: Uncaught TypeError: Cannot set properties of undefined (setting 'replace')
    at Object.isPrototypePolluted (file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/systeminformation/5.17.12/lib/util.js:719:24)
    at file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/systeminformation/5.17.12/lib/network.js:747:28
    at Array.forEach (<anonymous>)
    at file:///Users/username/Library/Caches/deno/npm/registry.npmjs.org/systeminformation/5.17.12/lib/network.js:733:16
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:23:21)
```

Any help / roadmap / wontfix would be appreciated!
Greetings, Alex

**Comment by Creative-Difficulty** [comment]
@sebhildebrandt

**Comment by Creative-Difficulty** [comment]
i guess not

**Comment by sebhildebrandt** [comment]
@Creative-Difficulty ... still investigating ... not yet clear, what changes this would need. I am currently also working on V6 (completely rewritten in TS) ... and here I probably can achieve demo compatibility.

**Comment by mountaindude** [comment]
+1 on Deno support being useful. 
Deno 2 adds a bunch of features making it a rather compelling option to good old Node.js..

I get a very similar error as @Creative-Difficulty , but for different parts of SystemInformation:


```javascript
const siCPU = await si.cpu();
const siSystem = await si.system();
const siMem = await si.mem();
const siOS = await si.osInfo();
const siDocker = await si.dockerInfo();
const siNetwork = await si.networkInterfaces();
```

All commands except the last one work.
`await si.networkInterfaces()` returns an error:

```
error: Uncaught TypeError: Cannot set properties of undefined (setting 'replace')
    at Object.isPrototypePolluted (file:///Users/username/code/projectname/node_modules/.deno/systeminformation@5.23.5/node_modules/systeminformation/lib/util.js:761:24)
    at file:///Users/goran/code/butler/node_modules/.deno/systeminformation@5.23.5/node_modules/systeminformation/lib/network.js:747:28
    at Array.forEach (<anonymous>)
    at file:///Users/goran/code/butler/node_modules/.deno/systeminformation@5.23.5/node_modules/systeminformation/lib/network.js:733:16
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:28:11)
    at runNextTicks (ext:deno_node/_next_tick.ts:75:3)
    at eventLoopTick (ext:core/01_core.js:182:21)
Process exited with code 1
```

Could it be that Deno doesn't support full set of Node.js network features..? Just guessing really.

**Comment by mountaindude** [comment]
Took a quick look and it seems SI uses __proto__.  in the isPrototypePolluted() function in lib/util.js.

But __proto__ is deprecated according to Mozilla.org and [not supported by Deno](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto#browser_compatibility).

**Comment by sebhildebrandt** [comment]
@mountaindude @Creative-Difficulty ... I am currently working on a completely rewritten new version 6.0 and finally got "caught" by `deno` :-)
For this new version I plan to have full deno2 compatibility. I am sorry that you guys needed to wait so long ...

**Comment by Creative-Difficulty** [comment]
No problem, thank you for wanting to implement it! I'm sure it will benefit many developers.

**Comment by sebhildebrandt** [comment]
@Creative-Difficulty @mountaindude I now also started to use System Information in Deno and had the same issue. I added a fix to the library that works here on my side. Can you test it also on your side? 

Please reopen this issue if you find more issues in deno.

Version 5.24.3 just released

**Comment by sebhildebrandt** [comment]
@Creative-Difficulty @mountaindude I tested all functions with deno ... seems to work fine (tested on M1 Mac)...

**Comment by sebhildebrandt** [comment]
@Creative-Difficulty I was now able to test it on macOS, linux and windows and it works in Deno on all platforms as expected :-)

**Comment by mountaindude** [comment]
> @Creative-Difficulty @mountaindude I tested all functions with Deno ... seems to work fine
> 
> * tested on M1 Mac
> * Deno 2.1.4
> 
> On Mac I see one issue on Denos side: `os.freemem()` seems to be wrong (missing multiplication by 1024). I see that there is already a fix for that on their side but not yet released.

I ended up ditching Deno and moved back to Node.js, as several of my projects depended on features not yet available in Deno. 
So I can't test your update unfortunately.

**Comment by sebhildebrandt** [comment]
@mountaindude ... no problem. I already tested it now on different platforms and as far as I can see nearly all works as expected. I see 2 compatibility issues on Denos side. Both are related to `os` functionality ... `os.freemem()` and `os.cpus()` have smaller issues. The first one is already fixed on Denos side. For the second one I opened an issue there.

**Comment by sebhildebrandt** [comment]
For everyone who is interested in Deno compatibility: Currently I see 2 issues

- on Denos side, `os.freemem()` calculated wrongg values (1024 times to low). This is already fixed on their side but not yet part of version 2.1.4 of deno. `mem()` therefore has incorrect values for now in `systeminformation`when using Deno 2.1.4
- on Denos side, `os.cpus()` has 0 values on the `speed` property. I opened an issue for that on their side. Not yet fixed. But I have implemented a workaround in `systeminformation` so that we see **correct values** in `cpuCurrentSpeed()`
