### ISSUE TITLE
The `systeminformation` fails on Gitlab's m1 macos runner

### ISSUE THREAD

**Issue by CMCDragonkai** [sebhildebrandt/systeminformation#823]
**Describe the bug**

Running 5.18.4 `systeminformation` on the m1 macos runners on GitLab results in this error:

```
Error: Command failed: ioreg -c IOPlatformDevice -d 3 -r | grep cluster-type
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at /Users/gitlab/builds/zxQ9CHzH/0/MatrixAI/open-source/js-db/node_modules/systeminformation/lib/cpu.js:652:32
    at ChildProcess.exithandler (node:child_process:411:7)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28) {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 34634,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}
```

Notice that it has `status` `1`. I confirmed that `ioreg` and `grep` exists, but because there's no `cluster-type` information, it returns with an exit code of `1`.

I believe m1 mac VMs on gitlab doesn't have cluster-type, and so this causes `systeminformation` to fail.

I'm using:

```
  const systemData = await si.get({
    cpu: '*',
    osInfo: 'platform, distro, release, kernel, arch',
    system: 'model, manufacturer',
  });
```

**To Reproduce**

Try using `systeminformation` in `saas-macos-medium-m1` with `macos-12-xcode-14`. This is a paid feature so it's not something you can easily reproduce.

**Current Output**

```
Error: Command failed: ioreg -c IOPlatformDevice -d 3 -r | grep cluster-type
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at /Users/gitlab/builds/zxQ9CHzH/0/MatrixAI/open-source/js-db/node_modules/systeminformation/lib/cpu.js:652:32
    at ChildProcess.exithandler (node:child_process:411:7)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28) {
  status: 1,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 34634,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}
```

**Expected behavior**

It should just ignore the command if the information doesn't exist.

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: [e.g. macOS] saas-macos-medium-m1
 - Hardware [e.g. MacBook Pro 13]

**Additional context**

**Comment by CMCDragonkai** [comment]
Here's the output from the m1 machine VM script:

<details>

```
$ ioreg -c IOPlatformDevice -d 3 -r
+-o cpu0@0  <class IOPlatformDevice, id 0x100000110, registered, matched, active, busy 0 (3 ms), retain 8>
  | {
  |   "IOInterruptSpecifiers" = (<0100000001000000>,<1700000001000000>,<0100000001000000>)
  |   "AAPL,phandle" = <11000000>
  |   "cpu-id" = <00000000>
  |   "fixed-frequency" = <00366e0100000000>
  |   "bus-frequency" = <00366e0100000000>
  |   "logical-cluster-id" = 0
  |   "cpu-version" = <00000000>
  |   "memory-frequency" = <00366e0100000000>
  |   "IOInterruptControllers" = ("IOInterruptController00000037","IOInterruptController00000037","IOInterruptController00000037")
  |   "name" = <"cpu0">
  |   "interrupt-parent" = <37000000>
  |   "state" = <"running">
  |   "compatible" = <"ARM,v8">
  |   "peripheral-frequency" = <00366e0100000000>
  |   "interrupts" = <010000000100000017000000010000000100000001000000>
  |   "timebase-frequency" = <00366e0100000000>
  |   "function-enable_core" = <>
  |   "clock-frequency" = <00366e0100000000>
  |   "device_type" = <"cpu">
  |   "logical-cpu-id" = 0
  |   "reg" = <00000000>
  | }
  | 
  +-o AppleARMCPU  <class AppleARMCPU, id 0x100000160, !registered, !matched, active, busy 0, retain 4>
+-o cpu1@1  <class IOPlatformDevice, id 0x100000111, registered, matched, active, busy 0 (3 ms), retain 8>
  | {
  |   "IOInterruptSpecifiers" = (<0100000001000000>,<1700000001000000>,<0100000001000000>)
  |   "AAPL,phandle" = <12000000>
  |   "cpu-id" = <01000000>
  |   "fixed-frequency" = <00366e0100000000>
  |   "bus-frequency" = <00366e0100000000>
  |   "logical-cluster-id" = 0
  |   "memory-frequency" = <00366e0100000000>
  |   "IOInterruptControllers" = ("IOInterruptController00000037","IOInterruptController00000037","IOInterruptController00000037")
  |   "name" = <"cpu1">
  |   "interrupt-parent" = <37000000>
  |   "state" = <"waiting">
  |   "compatible" = <"ARM,v8">
  |   "peripheral-frequency" = <00366e0100000000>
  |   "interrupts" = <010000000100000017000000010000000100000001000000>
  |   "timebase-frequency" = <00366e0100000000>
  |   "function-enable_core" = <>
  |   "clock-frequency" = <00366e0100000000>
  |   "device_type" = <"cpu">
  |   "logical-cpu-id" = 1
  |   "reg" = <01000000>
  | }
  | 
  +-o AppleARMCPU  <class AppleARMCPU, id 0x100000161, !registered, !matched, active, busy 0, retain 4>
+-o cpu2@2  <class IOPlatformDevice, id 0x100000112, registered, matched, active, busy 0 (3 ms), retain 8>
  | {
  |   "IOInterruptSpecifiers" = (<0100000001000000>,<1700000001000000>,<0100000001000000>)
  |   "AAPL,phandle" = <13000000>
  |   "cpu-id" = <02000000>
  |   "fixed-frequency" = <00366e0100000000>
  |   "bus-frequency" = <00366e0100000000>
  |   "logical-cluster-id" = 0
  |   "memory-frequency" = <00366e0100000000>
  |   "IOInterruptControllers" = ("IOInterruptController00000037","IOInterruptController00000037","IOInterruptController00000037")
  |   "name" = <"cpu2">
  |   "interrupt-parent" = <37000000>
  |   "state" = <"waiting">
  |   "compatible" = <"ARM,v8">
  |   "peripheral-frequency" = <00366e0100000000>
  |   "interrupts" = <010000000100000017000000010000000100000001000000>
  |   "timebase-frequency" = <00366e0100000000>
  |   "function-enable_core" = <>
  |   "clock-frequency" = <00366e0100000000>
  |   "device_type" = <"cpu">
  |   "logical-cpu-id" = 2
  |   "reg" = <02000000>
  | }
  | 
  +-o AppleARMCPU  <class AppleARMCPU, id 0x100000162, !registered, !matched, active, busy 0, retain 4>
+-o cpu3@3  <class IOPlatformDevice, id 0x100000113, registered, matched, active, busy 0 (3 ms), retain 8>
  | {
  |   "IOInterruptSpecifiers" = (<0100000001000000>,<1700000001000000>,<0100000001000000>)
  |   "AAPL,phandle" = <14000000>
  |   "cpu-id" = <03000000>
  |   "fixed-frequency" = <00366e0100000000>
  |   "bus-frequency" = <00366e0100000000>
  |   "logical-cluster-id" = 0
  |   "memory-frequency" = <00366e0100000000>
  |   "IOInterruptControllers" = ("IOInterruptController00000037","IOInterruptController00000037","IOInterruptController00000037")
  |   "name" = <"cpu3">
  |   "interrupt-parent" = <37000000>
  |   "state" = <"waiting">
  |   "compatible" = <"ARM,v8">
  |   "peripheral-frequency" = <00366e0100000000>
  |   "interrupts" = <010000000100000017000000010000000100000001000000>
  |   "timebase-frequency" = <00366e0100000000>
  |   "function-enable_core" = <>
  |   "clock-frequency" = <00366e0100000000>
  |   "device_type" = <"cpu">
  |   "logical-cpu-id" = 3
  |   "reg" = <03000000>
  | }
  | 
  +-o AppleARMCPU  <class AppleARMCPU, id 0x100000163, !registered, !matched, active, busy 0, retain 4>
+-o machine-timeouts  <class IOPlatformDevice, id 0x100000101, registered, matched, active, busy 0 (3 ms), retain 6>
    {
      "ticket-lock-scale" = <00000000>
      "sshot-interrupt-masked-scale" = <00000000>
      "lock-scale" = <00000000>
      "debug-ack-scale" = <00000000>
      "lock-panic-scale" = <00000000>
      "gicr-wake-timeout-scale" = <00000000>
      "interrupt-masked-b-scale" = <00000000>
      "interrupt-masked-scale" = <00000000>
      "AAPL,phandle" = <02000000>
      "name" = <"machine-timeouts">
    }
    
+-o cpus  <class IOPlatformDevice, id 0x10000010f, registered, matched, active, busy 0 (3 ms), retain 10>
    {
      "#address-cells" = <01000000>
      "#size-cells" = <00000000>
      "max_cpus" = <20000000>
      "name" = <"cpus">
      "AAPL,phandle" = <10000000>
    }
    
+-o pmgr  <class IOPlatformDevice, id 0x100000116, registered, matched, active, busy 0 (4 ms), retain 7>
  | {
  |   "compatible" = <"ARM,psci">
  |   "name" = <"pmgr">
  |   "AAPL,phandle" = <33000000>
  | }
  | 
  +-o ApplePSCI  <class ApplePSCI, id 0x100000164, registered, matched, active, busy 0 (0 ms), retain 6>
+-o arm-io  <class IOPlatformDevice, id 0x100000117, registered, matched, active, busy 0 (572 ms), retain 15>
  | {
  |   "ranges" = <000000000000000000000010000000000000007000000000>
  |   "compatible" = <"arm-io,vmapple1">
  |   "#size-cells" = <02000000>
  |   "chip-revision" = <00000000>
  |   "device_type" = <"vmapple2-io">
  |   "fuse-revision" = <00000000>
  |   "soc-generation" = <"VMApple2">
  |   "#address-cells" = <02000000>
  |   "name" = <"arm-io">
  |   "AAPL,phandle" = <34000000>
  | }
  | 
  +-o AppleVirtualPlatformIO  <class AppleVirtualPlatformIO, id 0x100000165, !registered, !matched, active, busy 0 (568 ms), retain 12>
    +-o aes@20220000  <class AppleARMIODevice, id 0x100000118, registered, matched, active, busy 0 (406 ms), retain 8>
    +-o gic@0  <class AppleARMIODevice, id 0x100000119, registered, matched, active, busy 0 (6 ms), retain 9>
    +-o rtc@10050000  <class AppleARMIODevice, id 0x10000011a, registered, matched, active, busy 0 (10 ms), retain 8>
    +-o pvpanic@10070000  <class AppleARMIODevice, id 0x10000011b, registered, matched, active, busy 0 (6 ms), retain 8>
    +-o pcie@30000000  <class AppleARMIODevice, id 0x10000011c, registered, matched, active, busy 0 (379 ms), retain 16>
    +-o pl061-buttons@10060000  <class AppleARMIODevice, id 0x10000011d, registered, matched, active, busy 0 (8 ms), retain 9>
    +-o iosurface-mapper@20210000  <class AppleARMIODevice, id 0x10000011e, registered, matched, active, busy 0 (9 ms), retain 9>
    +-o gfx@20200000  <class AppleARMIODevice, id 0x10000011f, registered, matched, active, busy 0 (14 ms), retain 8>
+-o pram@70794000  <class IOPlatformDevice, id 0x100000120, registered, matched, active, busy 0 (3 ms), retain 6>
    {
      "IODeviceMemory" = (({"address"=10476929024,"length"=2080768}))
      "reg" = <004079700200000000c01f0000000000>
      "name" = <"pram">
      "AAPL,phandle" = <3e000000>
      "device_type" = <"pram">
    }
    
+-o vram@6FF40000  <class IOPlatformDevice, id 0x100000121, registered, matched, active, busy 0 (3 ms), retain 7>
    {
      "IODeviceMemory" = (({"address"=10468196352,"length"=8732672}))
      "reg" = <0000f46f020000000040850000000000>
      "name" = <"vram">
      "AAPL,phandle" = <3f000000>
      "device_type" = <"vram">
    }
    
+-o defaults  <class IOPlatformDevice, id 0x100000122, registered, matched, active, busy 0 (410 ms), retain 8>
  | {
  |   "vmm-present" = <01000000>
  |   "AAPL,phandle" = <40000000>
  |   "name" = <"defaults">
  |   "ean-storage-present" = <>
  |   "kern.vm_compressor" = <04000000>
  |   "avp-encryption-version" = <00000000>
  |   "force-sep-nonce" = <01000000>
  |   "pmap-max-asids" = <00400000>
  |   "no-effaceable-storage" = <>
  |   "sleep-disabled" = <01000000>
  | }
  | 
  +-o AppleImage4  <class AppleImage4, id 0x100000166, registered, matched, active, busy 0 (0 ms), retain 6>
  +-o AppleMobileApNonce  <class AppleMobileApNonce, id 0x100000167, registered, matched, active, busy 0 (0 ms), retain 5>
+-o product  <class IOPlatformDevice, id 0x100000123, registered, matched, active, busy 0 (3 ms), retain 8>
    {
      "graphics-featureset-fallbacks" = <"APPLE6:APPLE5:APPLE4:APPLE3:APPLE3v1:APPLE2:APPLE1:GLES2,0">
      "location-reminders" = <00000000>
      "device-perf-memory-class" = <10000000>
      "artwork-device-subtype" = <00000000>
      "product-description" = <"virtual machine for ARM-v8.4 with Apple Silicon extensions">
      "builtin-mics" = <00000000>
      "allow-32bit-apps" = <01000000>
      "compatible-device-fallback" = <"iPad8,6">
      "mobiledevice-beta-min-ver" = <"1190.100.2">
      "product-soc-name" = <"Apple M1 (Virtual)">
      "sandman-support" = <00000000>
      "atomic-firmware-update-support" = <01000000>
      "RF-exposure-separation-distance" = <05000000>
      "single-stage-boot" = <01000000>
      "dali-mode" = <00000000>
      "AAPL,phandle" = <41000000>
      "allow-hactivation" = <01000000>
      "name" = <"product">
      "graphics-featureset-class" = <"APPLE7">
      "mobiledevice-min-ver" = <"1351">
      "apple-guest-agent-port" = <dab40700>
      "compatible-app-variant" = <"MacFamily20,1">
      "ui-weather-quality" = <64000000>
      "artwork-dynamic-displaymode" = <"0">
      "dual-iboot-support" = <01000000>
      "assistant" = <00000000>
      "product-name" = <"Apple Virtual Machine 1">
      "product-id" = <23f17bc00dc6eab8162e14033bea91e057f61510>
      "udid-version" = <02000000>
      "bluetooth-le" = <00000000>
      "ephemeral-data-mode" = <00000000>
      "lockdown-certtype" = <00000000>
      "dictation" = <00000000>
      "artwork-scale-factor" = <02000000>
      "artwork-device-idiom" = <"mac">
      "artwork-display-gamut" = <"P3">
    }
    
+-o filesystems  <class IOPlatformDevice, id 0x100000126, registered, matched, active, busy 0 (3 ms), retain 9>
    {
      "name" = <"filesystems">
      "AAPL,phandle" = <44000000>
    }
    
+-o buttons  <class IOPlatformDevice, id 0x100000136, registered, matched, active, busy 0 (4 ms), retain 8>
  | {
  |   "name" = <"buttons">
  |   "DeviceOpenedByEventSystem" = Yes
  |   "AAPL,phandle" = <54000000>
  | }
  | 
  +-o AppleM68Buttons  <class AppleM68Buttons, id 0x100000168, registered, matched, active, busy 0 (0 ms), retain 8>
    +-o IOHIDEventServiceUserClient  <class IOHIDEventServiceUserClient, id 0x100000296, !registered, !matched, active, busy 0, retain 6>
```

</details>

Notice there's no `cluster-type` information.

**Comment by sebhildebrandt** [comment]
@CMCDragonkai fixed. Version 5.18.5 just released.

If you discover any other issues, please feel free to open a new issue here.

**Comment by CMCDragonkai** [comment]
Thanks, this fixed it.
