### ISSUE TITLE
Mac OS 12.7 - si.wifiNetworks() failing

### ISSUE THREAD

**Issue by shoustech** [sebhildebrandt/systeminformation#857]
**Describe the bug**
On my test MacBook Pro 13-inch 2016 when running the si.wifiNetworks() I recieve an error.

**To Reproduce**
1. On macOS Monterey run this node script with Node v18:
``` javascript
const si = require('systeminformation');

async function getNetworks() {
  console.log(await si.wifiNetworks());
}

getNetworks();
```

**Current Output**
```
{
  timestamp: '10/4/2023, 12:57:57 PM',
  level: 'error',
  fn: null,
  error: {
    message: 'The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type number (-82)',
    stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type number (-82)\n' +
      '    at new NodeError (node:internal/errors:399:5)\n' +
      '    at Function.from (node:buffer:339:9)\n' +
      '    at /Users/admin/Documents/Agent-Manager/node_modules/systeminformation/lib/wifi.js:371:23\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at parseWifiDarwin (/Users/admin/Documents/Agent-Manager/node_modules/systeminformation/lib/wifi.js:344:13)\n' +
      '    at /Users/admin/Documents/Agent-Manager/node_modules/systeminformation/lib/wifi.js:445:20\n' +
      '    at ChildProcess.exithandler (node:child_process:411:7)\n' +
      '    at ChildProcess.emit (node:events:513:28)\n' +
      '    at maybeClose (node:internal/child_process:1091:16)\n' +
      '    at ChildProcess._handle.onexit (node:internal/child_process:302:5)'
  },
  message: 'Unexpected error - logs found in journalctl'
}
```

Here is a console.log of the variable `wifiItem` from the function `parseWifiDarwin`

``` Javascript
{
  AGE: 0,
  AP_MODE: 2,
  BEACON_INT: 100,
  BSSID: '4a:d9:e7:ad:92:61',
  CAPABILITIES: 1073,
  CHANNEL: 1,
  CHANNEL_FLAGS: 10,
  HT_CAPS_IE: {
    AMPDU_PARAMS: 27,
    ASEL_CAPS: 0,
    CAPS: 428,
    EXT_CAPS: 0,
    MCS_SET: 0,
    TXBF_CAPS: 0
  },
  HT_IE: {
    HT_BASIC_MCS_SET: null,
    HT_DUAL_BEACON: false,
    HT_DUAL_CTS_PROT: false,
    HT_LSIG_TXOP_PROT_FULL: false,
    HT_NON_GF_STAS_PRESENT: false,
    HT_OBSS_NON_HT_STAS_PRESENT: false,
    HT_OP_MODE: 1,
    HT_PCO_ACTIVE: false,
    HT_PCO_PHASE: false,
    HT_PRIMARY_CHAN: 1,
    HT_PSMP_STAS_ONLY: false,
    HT_RIFS_MODE: false,
    HT_SECONDARY_BEACON: false,
    HT_SECONDARY_CHAN_OFFSET: 0,
    HT_SERVICE_INT: 0,
    HT_STA_CHAN_WIDTH: false,
    HT_TX_BURST_LIMIT: false
  },
  IE: {
    HT_BASIC_MCS_SET: null,
    HT_DUAL_BEACON: false,
    HT_DUAL_CTS_PROT: false,
    HT_LSIG_TXOP_PROT_FULL: false,
    HT_NON_GF_STAS_PRESENT: false,
    HT_OBSS_NON_HT_STAS_PRESENT: false,
    HT_OP_MODE: 1,
    HT_PCO_ACTIVE: false,
    HT_PCO_PHASE: false,
    HT_PRIMARY_CHAN: 1,
    HT_PSMP_STAS_ONLY: false,
    HT_RIFS_MODE: false,
    HT_SECONDARY_BEACON: false,
    HT_SECONDARY_CHAN_OFFSET: 0,
    HT_SERVICE_INT: 0,
    HT_STA_CHAN_WIDTH: false,
    HT_TX_BURST_LIMIT: false
  },
  NOISE: 0,
  RATES: [
     1,  2,  5,  6,  9,
    11, 12, 18, 24, 36,
    48, 54
  ],
  RSN_IE: {
    IE_KEY_RSN_AUTHSELS: [ 2 ],
    IE_KEY_RSN_MCIPHER: 4,
    IE_KEY_RSN_UCIPHERS: [ 4 ],
    IE_KEY_RSN_VERSION: 1
  },
  RSSI: -84,
  SSID: -84,
  SSID_STR: 'CutPrice-WiFi'
}
```
Here is the offending bit of code: `wifi.js line 370`
```
if (wifiItem.SSID) {
  ssid = Buffer.from(wifiItem.SSID, 'base64').toString('utf8');
}
```

**Expected behavior**
I would suggest adding a check to see if `ssid` is empty and if it is then attempt pulling from the wifiItem.SSID field because the `wifiItem.SSID_STR` is the correct value on my machine. Possibly wrap a try catch around Buffer.from so the error can be captured but ignored without crashing the function.

``` javascript
if (wifiItem.SSID && ssid === '') {
  try {
    console.log('Here')
    ssid = Buffer.from(wifiItem.SSID, 'base64').toString('utf8');
  } catch { }
}
```
**Environment (please complete the following information):**
 - systeminformation package version: 5.21.5
 - OS: macOS 12.7
 - Hardware Macbook Pro 2016 13 inch

To get all needed environment information, please run the following command:

```
┌─────────────────────────────────────────────────────────────────────────────────────────┐
│  SYSTEMINFORMATION                                                      Version: 5.21.5 │
└─────────────────────────────────────────────────────────────────────────────────────────┘

Operating System:
──────────────────────────────────────────────────────────────────────────────────────────
Platform         : darwin
Distro           : macOS
Release          : 12.7
Codename         : macOS Monterey
Kernel           : 21.6.0
Arch             : x64
Hostname         : somehost.host.local
Codepage         : UTF-8
Build            : 21G816

System:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : Apple Inc.
Model            : MacBookPro13,2
Version          : 1.0
Virtual          : 

CPU:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : Intel
Brand            : Core™ i7-6567U
Family           : 6
Model            : 78
Stepping         : 3
Speed            : 3.3
Cores            : 4
PhysicalCores    : 2
PerformanceCores : 4
EfficiencyCores  : 
Processors       : 1
Socket           : 
```

**Comment by sebhildebrandt** [comment]
Hi @shoustech , sorry ... my fault. You are absolutely right. Fixed it and published a new version 5.21.10.
