### ISSUE TITLE
si.processLoad on Windows10 not supported

### ISSUE THREAD

**Issue by ttsz** [sebhildebrandt/systeminformation#88]
### Issue Type

* [X ] Bug
* [X ] Feature Request
* [ ] Question

### Expected behavior 

Run and show windows process infos like cpuload, mem usage, disk usage

### Actual behavior

(node:2808) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: not supported
(node:2808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: not supported
    at process.nextTick (C:\nodelogger\node_modules\systeminformation\lib\processes.js:594:21)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:2808) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

### Steps to reproduce the problem

si.processLoad('java.exe')

### Specifications 

- package version: 3.33.1
- operating system: Windows 10 Enterprise
- hardware: 4th gen i7, 16GB Ram, SSD

### Problem and possible solution

I don't have any solution, it would be great if it work well. 
It's urgent for me and can it be solved.

**Comment by sebhildebrandt** [comment]
Hi @ttsz, 

As stated in the documentation, this is not yet available but I am working already on it but I am quite busy. Do not expect a quick solution. Will not have a solution before end of November.

**Comment by ttsz** [comment]
Hi! 
Thanks for the quick answer. I can wait until the end of November, so it would be great.

**Comment by nascarjake** [comment]
Any idea when this will be available? Sorry to necro a year old issue - this function would be very helpful but half of my users are on windows.
