### ISSUE TITLE
Problem with GPU metrics on Windows 24H2

### ISSUE THREAD

**Issue by TheRedfoox** [sebhildebrandt/systeminformation#914]
**Describe the bug**
Since the Windows 24H2 update, almost no GPU metrics (usage, temperature, power, etc.) come up. However, on another PC running Windows 23H2, the metrics come back correctly.

**To Reproduce**
1. Use the function `systeminformation.graphics()`.
2. Run the application
3. Observe GPU metrics

**Current Output**
GPU metrics (usage, temperature, power, etc.) are not available.

**Expected behavior**
GPU metrics (usage, temperature, power, etc.) should be available, as they are on a Windows 23H2 PC.

**Environment (please complete the following information):**
 - systeminformation package version: 5.22.11
 - OS: Windows 24H2
 - Hardware: i7 12700k, RTX 3080, 32Go RAM DDR4

To get all needed environment information, please run the following command:

```
┌─────────────────────────────────────────────────────────────────────────────────────────┐
│  SYSTEMINFORMATION                                                     Version: 5.22.11 │
└─────────────────────────────────────────────────────────────────────────────────────────┘

Operating System:
──────────────────────────────────────────────────────────────────────────────────────────
Platform         : Windows
Distro           : Microsoft Windows 11 Professionnel
Release          : 10.0.26100
Codename         : 
Kernel           : 10.0.26100
Arch             : x64
Hostname         : NZXT-DU-RENARD
Codepage         : 850
Build            : 26100
Hypervisor       : true
RemoteSession    :

System:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : ASUS
Model            : System Product Name
Version          : System Version
Virtual          :

CPU:
──────────────────────────────────────────────────────────────────────────────────────────
Manufacturer     : Intel
Brand            : Gen Intel® Core™ i7-12700K
Family           : 6
Model            : 151
Stepping         : 2
Speed            : 3.61
Cores            : 20
PhysicalCores    : 12
PerformanceCores : 20
EfficiencyCores  :
Processors       : 1
Socket           : Other
```

**Additional context**
This problem appeared after the Windows 24H2 update. On another PC running Windows 23H2, GPU metrics are correctly displayed.

**Comment by TheRedfoox** [comment]
After putting a few debuggers in the code, I realize that getNvidiaSmi() is in error

```
Line 397: Error: ENOTDIR: not a directory, scandir 'C:\WINDOWS\System32\DriverStore\FileRepository/a-volutenh3aposwc.inf_amd64_b9b81cb814cdca75.ini'
    at Object.readdirSync (VM262 node:fs:1527:3)
    at t.readdirSync (VM340 node_init:2:11289)
    at VM369 G:\Developer\sb-hardware-monitor\node_modules\systeminformation\lib\graphics.js:398:21
    at Array.filter (<anonymous>)
    at getNvidiaSmi (VM369 G:\Developer\sb-hardware-monitor\node_modules\systeminformation\lib\graphics.js:397:56)
    at nvidiaSmi (VM369 G:\Developer\sb-hardware-monitor\node_modules\systeminformation\lib\graphics.js:420:26)
    at nvidiaDevices (VM369 G:\Developer\sb-hardware-monitor\node_modules\systeminformation\lib\graphics.js:444:20)
    at VM369 G:\Developer\sb-hardware-monitor\node_modules\systeminformation\lib\graphics.js:837:30
    at process.processTicksAndRejections (VM225 task_queues:77:11)
```

**Comment by TheRedfoox** [comment]
With even more searching, I see that `fs.readdirSync(basePath)` would expect to have only directories but actually with my explorer here `C:\Windows\System32\DriverStore\FileRepository` I see .ini's which may have the same name as some folders.

I think that since Windows 24H2 there are files in FileRepository, which wasn't the case before and which now poses a problem.

**Comment by TheRedfoox** [comment]
Something like this should solve the problem by simply checking whether the element we're testing is actually a directory.

```
const candidateDirs = fs.readdirSync(basePath).filter(dir => {
  if (fs.statSync([basePath, dir].join('/')).isDirectory()) {
    return fs.readdirSync([basePath, dir].join('/')).includes('nvidia-smi.exe');
  }
});
```

I don't know if it's up to me to make a pull request or how to format it to propose this change to fix this problem on Windows 24H2.
In any case, I'm available to fix this problem as soon as possible.

**Comment by sebhildebrandt** [comment]
Hi @TheRedfoox ... seems that I completely forgot about this issue ... SORRY. I made some modifications in the `master` branch ... are you able to test it on your side?

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

Then press the `g` key to test graphics ...

Thank you in advance. If this solved the issue, I will release a new version with this fix.

**Comment by TheRedfoox** [comment]
No problem! In the meantime I had an npm patch. I'll watch and test it tonight and I'll tell you the result 👌🏻

**Comment by sebhildebrandt** [comment]
@TheRedfoox Version 5.27.17 published, can you check it on your side?

**Comment by TheRedfoox** [comment]
Hi @sebhildebrandt and sorry for the (very) long response time, I was on vacation. I just tried and it doesn't solve the path problem under Windows 11

Here is the patch I apply to precisely manage this case where there may be folders in the DriverStore

[systeminformation-npm-5.30.5-18dedcb8aa.patch](https://github.com/user-attachments/files/24723863/systeminformation-npm-5.30.5-18dedcb8aa.patch)

**Comment by sebhildebrandt** [comment]
Hi @TheRedfoox ... thank you for testing and providing your fix ... I applied it to the **master** branch ... can you once again test it? 

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

Then press the `g` key to test graphics ...

Thank you so much for your support.

**Comment by TheRedfoox** [comment]
Hi @sebhildebrandt, I did tests again, the call to `sanitizeShellString` poses a problem depending on the platforms ( / or \ ). By adding double quotes and use `path.join` to build the path we avoid any possibility of injections in the command.

I updated my patch here

[systeminformation-npm-5.30.5-18dedcb8aa.patch](https://github.com/user-attachments/files/24765308/systeminformation-npm-5.30.5-18dedcb8aa.patch)

**Comment by sebhildebrandt** [comment]
@TheRedfoox ... thank you I get the point ... 

Can you once again test the master branch?

**Comment by TheRedfoox** [comment]
Hi @sebhildebrandt, I just tried and it works great with the master 👌🏻

**Comment by sebhildebrandt** [comment]
@TheRedfoox Version  5.30.6 just released
